telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_CHAT_ID"
events:
  path: "./events.jsonl"
notify:
  min_interval_sec_per_symbol: 300
  send_go_off: false
  include_snapshot: true
commands:
  top_n_default: 10
